version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://nexen-admin:nexen1234@cluster0.j6msih2.mongodb.net/nexen?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"